name: C++ SFML Platformer CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SFML dependencies
      run: |
        sudo apt update
        sudo apt install -y libsfml-dev

    - name: Build the project
      run: |
        make clean
        make

    - name: Run tests
      run: |
        make test
